### ISSUE TITLE
Provide official AppImage builds for Linux

### ISSUE THREAD

**Issue by stavpup** [flagello/Essence#9]
Please provide Essence in the AppImage format for Linux. This would allow users to

Test Essence without having to install it
Use Essence on machines where they have no root rights
Run Essence on Linux distributions for which no native package is provided
AppImage is a bundling format for Linux that lets users download one single file, set the executable bit and run the application (here: Essence). Unlike other options, AppImage is entirely distribution-agnostic and no special runtime infrastructure is needed on the target system(s). This means that the user can run the application on almost any recent Linux distribution.

It is easy to convert the official deb builds to AppImages using this script.

**Comment by flagello** [comment]
Hi @stavpup! I wouldn't be able to test the build(s), sorry!
